### ISSUE TITLE
Settings window popping up

### ISSUE THREAD

**Issue by jeremyj** [JackDinn/tbtray#2]
Hi,

In Kubuntu 18.04 I installed the following packages: 
```
thunderbird (1:60.2.1+build1-0ubuntu0.18.04.2)
wmctrl
xdotool
python-pyqt5.qtmultimedia
python3-pyqt5.qtmultimedia
```
but the settings window keeps popping up with no way of closing it.

tbtray logs the following console error:
```QCoreApplication::postEvent: Unexpected null receiver```

**Comment by JackDinn** [comment]
have you set up at least 1 thunderbird account ? because it will keep trying until it has at least 1

**Comment by JackDinn** [comment]
Make sure that as well as there being at least 1 real thunderbird account setup in TBtray you must also make sure there are no "incorrect" items in the profiles box. So double check all of the items listed in the profiles box are correctly pointing to actual thunderbird INBOX.msf accounts. If TBtray finds any errors in the list it will keep popping up until the user fixes it.

![pic](https://i.imgur.com/K1sbKGw.png)

**Comment by jeremyj** [comment]
HI,

I reinstalled TB, deleted and recreated my profile and now the setup seems to work.

Now I'm facing these issues:
1. With TB already running: if I launch tbtray everything seems to works fine. But if I close the TB window then click on tbtray, the TB window will not open and I get this error:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  8 (X_MapWindow)
  Resource id in failed request:  0x2600011
  Serial number of failed request:  18
  Current serial number in output stream:  20
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x2600011
  Serial number of failed request:  26
  Current serial number in output stream:  26
```
Minimizing TB window or clicking on tbtray to minimize works fine.

2. With TB **not** running if I launch tbtray it will start TB but there is no tbtray icon in the systray. If I close the TB window, the tbtray icon appears in the systray but I'm back to issue 1.

**Comment by JackDinn** [comment]
yea, your not supposed to close the TB window on its own because it just leaves tbtray running and it then cant see TB. **Basically just use TBtray as your new TB launcher(make a launcher in your menu that launches tbtray)**. You _can_ run tbtray while TB is already running and it will work but running TBtray without TB is pointless and will generate errors because it cant see TB (you can just ignore them).

**Comment by jeremyj** [comment]
What I'm saying is that using tbtray as a launcher does not work.
To get it working i must first have TB running then launch tbtray.

**Comment by JackDinn** [comment]
does typing "thunderbird" into your terminal run TB ?

**Comment by jeremyj** [comment]
yes

**Comment by JackDinn** [comment]
what about 
>thunderbird > /dev/null 2>&1 & disown

**Comment by jeremyj** [comment]
ok my bad.
I had modified your script because I was getting
```
sh: 1: disown: not found
```
I accidentally removed the ``&`` too.
I put it back and now tbtray is working as expected.

Thanks

**Comment by JackDinn** [comment]
No problem. i shall close this thread now if thats ok ? 

cheers.

**Comment by jeremyj** [comment]
sure.

thanks for the support and for the nice work.

cheers!

**Comment by JackDinn** [comment]
Actually thinking about it I shall see if i can figure a way to close down tbtray if the user closes TB as it seems to confuse if i leave tbtray running after the user closes TB.

I should have thought about it already really but you just reminded me.

**Comment by jeremyj** [comment]
I think that would be a nice feature.
Even better would be to keep TB running even if the window is closed and leave all control to tbtray. But I don't know if that's possible with a wrapper like tbtray.

**Comment by JackDinn** [comment]
yea it would be nice to do that but i honestly cannot think of an easy way to intercept the signal that TB send to close itself. The other chap who is also developing a very similar app has come across the exact same problem. So closing everything on TB close is the best i can do.

p.s.
(I built this one to see if i could get the cpu down lower than 7% when idle ^^) https://github.com/gyunaev/birdtray/issues/26

**Comment by jeremyj** [comment]
yes I tried birdtray but I had some issues so I switched to yours ;-)

**Comment by JackDinn** [comment]
I need to ask you something. do you not have qt5-multimedia on Kubuntu 18.04 ? 
why did you install python-pyqt5.qtmultimedia & python3-pyqt5.qtmultimedia ?

Im just trying to figure a dependency checker but if different distros need different packages then that may be a problem for me.

**Comment by jeremyj** [comment]
when I did a search on apt for qt5-multimedia the closest thing I could find were those two python packages. I don't know if they're used or not. If you need me to, I could try uninstalling them to see what happens.

**Comment by JackDinn** [comment]
you'll probably get not sound notification (if your using it via TBtray) as thats what its for. Hmm well that makes things a little more complex for me, maybe i shall not bother with a dependency check cos who knows what other distros QSound package names are. dam. 

You can try it though, maybe whatever is needed to run QSound is already installed on Kubuntu.

Cheers.
