### ISSUE TITLE
Subprocess

### ISSUE THREAD

**Issue by rnc** [JackDinn/tbtray#8]
Why not use xauthentication as a native python library rather than xdotool?

Further could the number of subprocess be avoided - I notice a tail process which seems wasteful?

**Comment by JackDinn** [comment]
> Why not use xauthentication as a native python library rather than xdotool?

Never heard of it. I think i asked several places what i should use to minimize/hide/iconify the thunderbird window and xdotool and wmctrl were just about all i got.
 
> Further could the number of subprocess be avoided - I notice a tail process which seems wasteful?

I cant really remember, i think i used tail to monitor the INBOX.msf file every half a second in a really rough manor, i got it to work after weeks of my amateur poking around.

I'm not changing anything now, i cant remember much about how/what i did and I'm off doing completely different things now. If it breaks i might take a quick look but I'm kinda hoping there is actually a proper linux tray for thunderbird sorted out by then. (im sure i heard that firetray had been updated not long ago)

**Comment by geckolinux** [comment]
They've been trying to make Firetray work with TB 68+  but no success thus far.
https://github.com/Ximi1970/FireTray/issues/47

Birdtray's legacy sqlite parsing method doesn't work with TB 68+, and the Mork parser doesn't work with my large and complex inboxes.

So basically tbtray is my only hope...

**Comment by JackDinn** [comment]
> So basically tbtray is my only hope...

So did you manage to get it to work? i did not see any response on your [thread](https://github.com/JackDinn/tbtray/issues/5). If you have not you should try just a standard single INBOX.msf on its own just as a test, if you can get it to work you can build up numbers of inbox's from there. As i say on your thread, it's likely a problem with your .msf files somehow corrupt or being miss-read by TBtray so a new single test INBOX.msf's and/or a process of elimination and tinkering.

>They've been trying to make Firetray work with TB 68+ but no success thus far.
Ximi1970/FireTray#47

>Birdtray's legacy sqlite parsing method doesn't work with TB 68+, and the Mork parser doesn't work with my large and complex inboxes.

Hmm, i knew there were problems with thundebird and the linux tray hence why i built this but i didn't know they were still having so much trouble. Its still working fine for me, i use about 7 inboxs.

Interesting though.

**Comment by geckolinux** [comment]
@JackDinn  Hmmm, appears I spoke too soon. I just compiled the latest GIT version of Birdtray, and back when you suggested that I regenerated my INBOX.msf files I did so. So Birdtray is now working with the Mork parser for all my configured accounts, which wasn't the case before. I'm not sure if it's the latest GIT version or the .msf regen, but for now it's working for me.

At any rate, I'm glad that an alternative exists to Birdtray, because this functionality is just too important to not have. I'm personally not holding my breath on Firetray, and even less so for ever getting native tray support in Thunderbird. And it appears particularly unlikely for Linux, with the tray standard being so fragmented and some desktops even trying to eliminate it.

**Comment by JackDinn** [comment]
@geckolinux 
Agreed it's a mess. There is Mailspring but even though some say its tray does work on most linux distro's it just will not for me on Manjaro KDE and then there is Kontact and/or kmail (if you like akonadi :-/) Great tray integration but I could not get on with it and not for lack of trying. As for the other mail clients for linux ..well meh na.
So in the end after months of testing just about all the mail clients I'd had enough. Suppose im lucky i had enough programming background to be able to knock up tbtray which has been good for the last year or so, although i do panic every time they release an update for Thunderbird.
