### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by cwm77** [JackDinn/tbtray#9]
Hi JackDinn,

I tried to get your Thunderbird Tray Tool running, but failed. OS is Manjaro KDE.

It starts, but quits immediately with

TypeError: expected str, bytes or os.PathLike object, not int

What could the causing error be? Any Ideas?

Cheers,
cwm77

**Comment by JackDinn** [comment]
How did you run it ? it must have given more output info i.e. a line number where the error is thrown from.
Can you paste the whole error.

**Comment by cwm77** [comment]
I´m running it within a Terminal session and this is the whole output from start to end.

Icon theme "elementary" not found.
Icon theme "deepin" not found.
Traceback (most recent call last):
  File "tbtray/tbtray.py", line 555, in fire
    subprocess.run(["xdotool", "windowunmap", self.windowid])
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by JackDinn** [comment]
hmm, so can you check that you have installed xdotool, 
> pacman -Qi xdotool
if not please install it 
> pacman -S xdotool

Could you please post a copy of the log.txt file which is inside the tbtray folder after you have run tbtray at least once, i just need the last session (after the `TBtray started ################################################` part)

**Comment by cwm77** [comment]
xdotool is already installed.

These are the last lines of the log.txt:

19-11-22 14:56:10 TBtray started ################################################
19-11-22 14:56:10 get screen height 1050
19-11-22 14:56:10 get screen height 1050

**Comment by JackDinn** [comment]
can you paste a copy of the output from 
`> wmctrl -lx`
Execute it whilst thunderbird is running though ! It should contain "Mail.Thunderbird" within one of the lines.

**Comment by JackDinn** [comment]
Also i can you check if you have this temp file on your system and if you do please delete it
`/tmp/tbpassover`
Then retry TBtray

**Comment by cwm77** [comment]
That´s it! I deleted the file and now it runs! Thank you

**Comment by JackDinn** [comment]
weird one, that file should only be created if you click the TBtray shortcut icon (if you created one) whilst TBtray is already running. 
O well i seen odder things.
